
version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sql:/docker-entrypoint-initdb.d  # scripts mounted (you'll run them via sqlcmd)
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  api:
    build:
      context: .
      dockerfile: ./HelpDesk360.API/Dockerfile
    container_name: helpdesk360_api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HelpDesk360;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: helpdesk360_frontend
    working_dir: /app
    volumes:
      - ./helpdesk360-frontend:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "4200:4200"
    environment:
      - NG_CLI_ANALYTICS=false
    depends_on:
      - api

volumes:
  mssql_data:
