version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: helpdesk360-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong@Passw0rd"
      MYSQL_DATABASE: "HelpDesk360"
      MYSQL_USER: "helpdesk360"
      MYSQL_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - helpdesk360-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_VALUE_ON_ZERO
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYourStrong@Passw0rd"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # HelpDesk360 Backend API
  helpdesk360-api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.api
    container_name: helpdesk360-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=HelpDesk360;uid=root;pwd=YourStrong@Passw0rd;charset=utf8mb4;AllowPublicKeyRetrieval=true;
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - helpdesk360-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
   build:
     context: ./helpdesk360-frontend
     dockerfile: Dockerfile
   container_name: helpdesk360-frontend
   ports:
      - "4200:80"
   environment:
      - API_URL=http://helpdesk360-api:8080
   depends_on:
      - helpdesk360-api
   networks:
      - helpdesk360-network


volumes:
  mysql_data:
    driver: local

networks:
  helpdesk360-network:
    driver: bridge
